name = "EqualRanges"
uuid = "ff7c5f4f-a3ba-44b8-a276-2626f44d1d8f"
authors = ["Andrew Radcliffe <andrew.radcliffe@intel.com> and contributors"]
version = "0.1.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
